// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicianFinder_Back.Infrastructure;

#nullable disable

namespace MusicianFinder_Back.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324131837_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicianFinder.Domain.Models.Conversation", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConversationId"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastRead")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.ConversationParticipant", b =>
                {
                    b.Property<long>("ConvPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConvPartId"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("MusicianId")
                        .HasColumnType("bigint");

                    b.HasKey("ConvPartId")
                        .HasName("PK_ConversParticip");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MusicianId");

                    b.ToTable("Convers_Particip", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentId"));

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instrument", (string)null);

                    b.HasData(
                        new
                        {
                            InstrumentId = 1,
                            InstrumentName = "Chant masculin"
                        },
                        new
                        {
                            InstrumentId = 2,
                            InstrumentName = "Chant féminin"
                        },
                        new
                        {
                            InstrumentId = 3,
                            InstrumentName = "Guitare acoustique"
                        },
                        new
                        {
                            InstrumentId = 4,
                            InstrumentName = "Guitare électrique"
                        },
                        new
                        {
                            InstrumentId = 5,
                            InstrumentName = "Lap-Steel"
                        },
                        new
                        {
                            InstrumentId = 6,
                            InstrumentName = "Basse"
                        },
                        new
                        {
                            InstrumentId = 7,
                            InstrumentName = "Batterie"
                        },
                        new
                        {
                            InstrumentId = 8,
                            InstrumentName = "Percussions d’orchestre"
                        },
                        new
                        {
                            InstrumentId = 9,
                            InstrumentName = "Piano"
                        },
                        new
                        {
                            InstrumentId = 10,
                            InstrumentName = "Claviers/Synth"
                        },
                        new
                        {
                            InstrumentId = 11,
                            InstrumentName = "Clavecin"
                        },
                        new
                        {
                            InstrumentId = 12,
                            InstrumentName = "Orgue classique"
                        },
                        new
                        {
                            InstrumentId = 13,
                            InstrumentName = "Violon/Alto"
                        },
                        new
                        {
                            InstrumentId = 14,
                            InstrumentName = "Violoncelle"
                        },
                        new
                        {
                            InstrumentId = 15,
                            InstrumentName = "Contrebasse"
                        },
                        new
                        {
                            InstrumentId = 16,
                            InstrumentName = "Trompette"
                        },
                        new
                        {
                            InstrumentId = 17,
                            InstrumentName = "Trombone"
                        },
                        new
                        {
                            InstrumentId = 18,
                            InstrumentName = "Saxophone"
                        },
                        new
                        {
                            InstrumentId = 19,
                            InstrumentName = "Tuba"
                        },
                        new
                        {
                            InstrumentId = 20,
                            InstrumentName = "Clarinette"
                        },
                        new
                        {
                            InstrumentId = 21,
                            InstrumentName = "Flûte traversière"
                        },
                        new
                        {
                            InstrumentId = 22,
                            InstrumentName = "Hautbois/Basson"
                        },
                        new
                        {
                            InstrumentId = 23,
                            InstrumentName = "Cornemuse"
                        },
                        new
                        {
                            InstrumentId = 24,
                            InstrumentName = "Accordéon"
                        },
                        new
                        {
                            InstrumentId = 25,
                            InstrumentName = "Banjo"
                        },
                        new
                        {
                            InstrumentId = 26,
                            InstrumentName = "Luth"
                        },
                        new
                        {
                            InstrumentId = 27,
                            InstrumentName = "Turntable/DJ"
                        },
                        new
                        {
                            InstrumentId = 28,
                            InstrumentName = "Autre instrument acoustique"
                        },
                        new
                        {
                            InstrumentId = 29,
                            InstrumentName = "Autre instrument électrique"
                        },
                        new
                        {
                            InstrumentId = 30,
                            InstrumentName = "Autre instrument électronique"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Location", (string)null);

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationName = "Bruxelles"
                        },
                        new
                        {
                            LocationId = 2,
                            LocationName = "Brabant"
                        },
                        new
                        {
                            LocationId = 3,
                            LocationName = "Namur (ville)"
                        },
                        new
                        {
                            LocationId = 4,
                            LocationName = "Namur (province)"
                        },
                        new
                        {
                            LocationId = 5,
                            LocationName = "Liège (ville)"
                        },
                        new
                        {
                            LocationId = 6,
                            LocationName = "Liège (province)"
                        },
                        new
                        {
                            LocationId = 7,
                            LocationName = "Hainaut/Mons"
                        },
                        new
                        {
                            LocationId = 8,
                            LocationName = "Hainaut/Charleroi"
                        },
                        new
                        {
                            LocationId = 9,
                            LocationName = "Luxembourg"
                        },
                        new
                        {
                            LocationId = 10,
                            LocationName = "Anvers (ville)"
                        },
                        new
                        {
                            LocationId = 11,
                            LocationName = "Anvers (province)"
                        },
                        new
                        {
                            LocationId = 12,
                            LocationName = "Limbourg"
                        },
                        new
                        {
                            LocationId = 13,
                            LocationName = "Flandre Orientale"
                        },
                        new
                        {
                            LocationId = 14,
                            LocationName = "Flandre Occidentale"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("bit");

                    b.Property<long>("SenderMusicianId")
                        .HasColumnType("bigint");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderMusicianId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicStyle", b =>
                {
                    b.Property<int>("StyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StyleId"));

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StyleId");

                    b.ToTable("Music_Style", (string)null);

                    b.HasData(
                        new
                        {
                            StyleId = 1,
                            StyleName = "Pop"
                        },
                        new
                        {
                            StyleId = 2,
                            StyleName = "Rock"
                        },
                        new
                        {
                            StyleId = 3,
                            StyleName = "Metal"
                        },
                        new
                        {
                            StyleId = 4,
                            StyleName = "Punk/Hardcore"
                        },
                        new
                        {
                            StyleId = 5,
                            StyleName = "Rock alternatif/post/indie"
                        },
                        new
                        {
                            StyleId = 6,
                            StyleName = "Folk"
                        },
                        new
                        {
                            StyleId = 7,
                            StyleName = "Chanson"
                        },
                        new
                        {
                            StyleId = 8,
                            StyleName = "Electro"
                        },
                        new
                        {
                            StyleId = 9,
                            StyleName = "Rap/Hip-Hop"
                        },
                        new
                        {
                            StyleId = 10,
                            StyleName = "Soul"
                        },
                        new
                        {
                            StyleId = 11,
                            StyleName = "Funk"
                        },
                        new
                        {
                            StyleId = 12,
                            StyleName = "Jeune Public"
                        },
                        new
                        {
                            StyleId = 13,
                            StyleName = "Jazz"
                        },
                        new
                        {
                            StyleId = 14,
                            StyleName = "Classique/Contemporain"
                        },
                        new
                        {
                            StyleId = 15,
                            StyleName = "Baroque/Ancien"
                        },
                        new
                        {
                            StyleId = 16,
                            StyleName = "Chorale"
                        },
                        new
                        {
                            StyleId = 17,
                            StyleName = "Reggae"
                        },
                        new
                        {
                            StyleId = 18,
                            StyleName = "Blues"
                        },
                        new
                        {
                            StyleId = 19,
                            StyleName = "Trad/World"
                        },
                        new
                        {
                            StyleId = 20,
                            StyleName = "Country"
                        },
                        new
                        {
                            StyleId = 21,
                            StyleName = "Fanfare"
                        },
                        new
                        {
                            StyleId = 22,
                            StyleName = "Cover"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.Musician", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Arial");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Password_hashed");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("User");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("#000000");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Musician");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Misicians__Email");

                    b.ToTable("Musician", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicianLikesStyle", b =>
                {
                    b.Property<int>("MusicianStyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsMainStyle")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Main_Style");

                    b.Property<long>("MusicianId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicianId1")
                        .HasColumnType("bigint");

                    b.Property<int>("StyleId")
                        .HasColumnType("int");

                    b.HasKey("MusicianStyleId")
                        .HasName("PK_Musician_Styles");

                    b.HasIndex("MusicianId");

                    b.HasIndex("MusicianId1");

                    b.ToTable("Musician_Styles", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicianLocation", b =>
                {
                    b.Property<int>("MusicianLocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusicianLocId"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<long>("MusicianId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicianId1")
                        .HasColumnType("bigint");

                    b.HasKey("MusicianLocId")
                        .HasName("PK_Musician_Locations");

                    b.HasIndex("LocationId");

                    b.HasIndex("MusicianId");

                    b.HasIndex("MusicianId1");

                    b.ToTable("Musician_Locations", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicianPlaysInstrument", b =>
                {
                    b.Property<int>("MusInstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusInstrumentId"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMainInstrument")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Main_Instrument");

                    b.Property<long>("MusicianId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicianId1")
                        .HasColumnType("bigint");

                    b.HasKey("MusInstrumentId")
                        .HasName("PK_Musician_Instruments");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("MusicianId");

                    b.HasIndex("MusicianId1");

                    b.ToTable("Musician_Instruments", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicianProjectType", b =>
                {
                    b.Property<int>("MusProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusProjectId"));

                    b.Property<long>("MusicianId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicianId1")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int");

                    b.HasKey("MusProjectId")
                        .HasName("PK_Musician_Project_Types");

                    b.HasIndex("MusicianId");

                    b.HasIndex("MusicianId1");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Musician_Project_Types", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.ProjectType", b =>
                {
                    b.Property<int>("ProjectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectTypeId");

                    b.ToTable("Project_Type", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectTypeId = 1,
                            TypeName = "LongTermeSansGarantie"
                        },
                        new
                        {
                            ProjectTypeId = 2,
                            TypeName = "LongTermAvecGarantie"
                        },
                        new
                        {
                            ProjectTypeId = 3,
                            TypeName = "PonctuelSansGarantie"
                        },
                        new
                        {
                            ProjectTypeId = 4,
                            TypeName = "PonctuelAvecGarantie"
                        },
                        new
                        {
                            ProjectTypeId = 5,
                            TypeName = "Cours"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.ConversationParticipant", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Models.Musician", "Musician")
                        .WithMany()
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.Message", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Models.Musician", "SenderMusician")
                        .WithMany()
                        .HasForeignKey("SenderMusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderMusician");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicianLikesStyle", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Models.Musician", "Musician")
                        .WithMany()
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Models.Musician", null)
                        .WithMany("MusicStyles")
                        .HasForeignKey("MusicianId1");

                    b.HasOne("MusicianFinder.Domain.Models.MusicStyle", "MusicianStyle")
                        .WithMany()
                        .HasForeignKey("MusicianStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("MusicianStyle");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicianLocation", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Models.Musician", "Musician")
                        .WithMany()
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Models.Musician", null)
                        .WithMany("Locations")
                        .HasForeignKey("MusicianId1");

                    b.Navigation("Location");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicianPlaysInstrument", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Models.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Models.Musician", "Musician")
                        .WithMany()
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Models.Musician", null)
                        .WithMany("Instruments")
                        .HasForeignKey("MusicianId1");

                    b.Navigation("Instrument");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.MusicianProjectType", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Models.Musician", "Musician")
                        .WithMany()
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Models.Musician", null)
                        .WithMany("ProjectTypes")
                        .HasForeignKey("MusicianId1");

                    b.HasOne("MusicianFinder.Domain.Models.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Models.Musician", b =>
                {
                    b.Navigation("Instruments");

                    b.Navigation("Locations");

                    b.Navigation("MusicStyles");

                    b.Navigation("ProjectTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
